INSERT INTO tip (text, author) VALUES
("I am so clever that sometimes I don't understand a single word of what I am saying.", "Oscar Wilde"),
("I can resist everything except temptation.", "Oscar Wilde"),
("If at first you don’t succeed, then skydiving definitely isn’t for you.", "Steven Wright"),
("Age is of no importance unless you're a cheese.", "Billie Burke"),
("Behind every great man is a woman rolling her eyes.", "Jim Carrey"),
("I used to think I was indecisive, but now I'm not so sure.", "Unknown"),
("If you think nobody cares if you're alive, try missing a couple of car payments.", "Earl Wilson"),
("Never put off till tomorrow what you can do the day after tomorrow just as well.", "Mark Twain"),
("A day without laughter is a day wasted.", "Charlie Chaplin"),
("Before you judge someone, walk a mile in their shoes. That way, you’re a mile away and you have their shoes.", "Jack Handey"),
("You can’t have everything… where would you put it?", "Steven Wright"),
("I'm not arguing, I'm just explaining why I'm right.", "Unknown"),
("Common sense is like deodorant. The people who need it most never use it.", "Unknown"),
("Life is short. Smile while you still have teeth.", "Mallory Hopkins"),
("If you think you are too small to make a difference, try sleeping with a mosquito.", "Dalai Lama"),
("The road to success is always under construction.", "Lily Tomlin"),
("My bed is a magical place where I suddenly remember everything I was supposed to do.", "Unknown"),
("I always wanted to be somebody, but now I realize I should have been more specific.", "Lily Tomlin"),
("Why do they call it rush hour when nothing moves?", "Robin Williams"),
("If you can't dazzle them with brilliance, baffle them with nonsense.", "W.C. Fields");