INSERT INTO m8b (type, text) VALUES
(1, "Yes"),
(1, "Possible"),
(1, "Positive"),
(1, "Definitely"),
(1, "Without a doubt"),
(1, "Most likely"),
(1, "It is certain"),
(1, "Outlook good"),
(1, "Yes, in due time"),
(1, "Signs point to yes"),
(1, "You may rely on it"),
(1, "Absolutely"),
(1, "Affirmative"),
(0, "No"),
(0, "Impossible"),
(0, "Negative"),
(0, "Very doubtful"),
(0, "Don't count on it"),
(0, "Outlook not so good"),
(0, "My sources say no"),
(0, "Chances aren't good"),
(0, "Nope"),
(0, "Absolutely not"),
(0, "Unlikely"),
(0, "Not in this lifetime"),
(0, "I wouldn't bet on it");