/*
# VladOS Security

VladOS Security (shortly VOS) is a package used for all security related stuff inside VladOS the project.
Below are all features this package provides.

# Key Chain

TODO: add info

# Json Web Token functional

TODO: add info

# Password and Salt logic

TODO: add info

# Auth - VOS sub-package

TODO: add info
*/
package vos

//go:generate go tool github.com/princjef/gomarkdoc/cmd/gomarkdoc -o documentation.md

import "crypto/rand"

// Size of a salt that is generated by [GenerateSalt] in bytes.
const SaltSize int = 64

// Returns completly crypto random salt to use for password hashing.
func GenerateSalt() []byte {
	salt := make([]byte, SaltSize)
	rand.Read(salt)
	return salt
}

// PSH - Password Salted and Hashed.
//
// Function simplifies getting hashed password with given salt.
func GetPSH(password string, salt []byte) []byte {
	return nil // TODO: return something normal
}

// PSH - Password Salted and Hashed.
//
// Function simplifies validating that given PSH is for the given password and salt combination.
func ValidatePSH(password string, salt, psh []byte) bool {
	return false // TODO: return something normal
}
