/*
# VladOS Security

VladOS Security (shortly VOS) is a package used for all security related stuff inside VladOS the project.
Below are all features this package provides.

# Key Chain

TODO: add info

# Json Web Token functional

TODO: add info

# Password and Salt logic

TODO: add info

# Auth - VOS sub-package

TODO: add info
*/
package vos

//go:generate go tool github.com/princjef/gomarkdoc/cmd/gomarkdoc -o documentation.md

import (
	"crypto/rand"
	"reflect"

	"golang.org/x/crypto/argon2"
)

// Size of a salt that is generated by [GenerateSalt] in bytes.
const SaltSize int = 64

// Argon2 encryption specific parameters
const (
	PSH_TIME = 1
	PSH_MEM  = 64 * 1024
	PSH_THR  = 4
	PSH_LEN  = 64
)

// Returns completly crypto random salt to use for password hashing.
func GenerateSalt() []byte {
	salt := make([]byte, SaltSize)
	rand.Read(salt)
	return salt
}

// PSH - Password Salted and Hashed.
// Function simplifies getting hashed password with given salt.
func NewPSH(password string, salt []byte) []byte {
	return argon2.IDKey([]byte(password), salt, PSH_TIME, PSH_MEM, PSH_THR, PSH_LEN)
}

// PSH - Password Salted and Hashed.
// Function simplifies validating that given PSH is for the given password and salt combination.
func ValidatePSH(password string, salt, psh []byte) bool {
	got := argon2.IDKey([]byte(password), salt, PSH_TIME, PSH_MEM, PSH_THR, PSH_LEN)
	return reflect.DeepEqual(got, psh)
}
